version: '3'
services:

  psiturk:
    container_name: my-experiment
    build:
      context: .
      args:
        experiment_dir: /exp
    volumes:
      - ./exp:/exp
    tty: true
    stdin_open: true
    restart: unless-stopped

  db:
    container_name: my-experiment-db
    image: mysql:5.7
    volumes:
     - ./data/db:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: participants
      MYSQL_USER: paxton
      MYSQL_PASSWORD: psiturk

  adminer:
    container_name: my-experiment-adminer
    image: adminer:latest
    ports:
      - 127.0.0.1:8080:8080

  nginx:
    container_name: my-experiment-nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./exp:/var/www/exp:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf